language: ruby
rvm:
  - 2.2.1
before_script:
  - "mysql -e 'create database peatio_test;'"
  - "cp ./.travis.database.yml ./config/database.yml"
  - "cp ./.travis.application.yml ./config/application.yml"
  - "cp ./.travis.currencies.yml ./config/currencies.yml"
  - "cp ./.travis.markets.yml ./config/markets.yml"
  - "cp ./config/amqp.yml.example ./config/amqp.yml"
  - "mkdir -p ./tmp/cache"
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
notifications:
  slack: peatio:F2FWrCANEK3QcjHC16OO541l
