roles:
  - superadmin
  - admin
  - manager
  - accountant
  - compliance
  - support
  - technical
  - member
  - broker
  - trader
  - maker

admin_permissions:
  superadmin:
    manage:
      - Operations::Account
      - Operations::Asset
      - Operations::Expense
      - Operations::Liability
      - Operations::Revenue
      - Deposit
      - Withdraw
      - Account
      - PaymentAddress
      - Member
      - Engine
      - Market
      - Currency
      - Blockchain
      - TradingFee
      - WithdrawLimit
      - Wallet
      - Adjustment
      - Beneficiary
    read:
      - Trade
      - Order
    update:
      - Order
  admin:
    read:
      - Trade
      - Account
      - PaymentAddress
      - Member
      - Order
    update:
      - Order
      - Member
    manage:
      - Beneficiary
      - Operations::Account
      - Operations::Asset
      - Operations::Expense
      - Operations::Liability
      - Operations::Revenue
      - Engine
      - Market
      - Currency
      - Blockchain
      - Wallet
      - TradingFee
      - WithdrawLimit
      - Adjustment
      - PaymentAddress
      - Deposit
      - Withdraw
  accountant:
    read:
      - Operations::Account
      - Operations::Asset
      - Operations::Expense
      - Operations::Liability
      - Operations::Revenue
      - Member
      - Deposit
      - Withdraw
      - Account
      - PaymentAddress
      - Beneficiary
    update:
      - Deposit
      - Withdraw
    create:
      - Deposits::Fiat
      - Adjustment
  compliance:
    read:
      - Operations::Account
      - Operations::Asset
      - Operations::Expense
      - Operations::Liability
      - Operations::Revenue
      - Member
      - Deposit
      - Withdraw
      - Account
      - PaymentAddress
      - Beneficiary
    update:
      - Deposit
      - Withdraw
  manager:
    read:
      - Operations::Account
      - Operations::Asset
      - Operations::Expense
      - Operations::Liability
      - Operations::Revenue
      - Deposit
      - Withdraw
      - Account
      - PaymentAddress
      - Beneficiary
      - Member
      - Trade
      - Order
    update:
      - Currency:
        - name
        - position
        - icon_url
      - Blockchain:
        - name
        - explorer_address
        - explorer_transaction
  support:
    read:
      - Deposit
      - Withdraw
      - Account
      - Member
  technical:
    read:
      - Operations::Account
      - Operations::Asset
      - Operations::Expense
      - Operations::Liability
      - Operations::Revenue
      - Deposit
      - Withdraw
      - Account
      - PaymentAddress
      - Beneficiary
      - Member
    manage:
      - Engine
      - Market
      - Currency
      - Blockchain
      - TradingFee
      - WithdrawLimit
      - Wallet

user_permissions:
  member:
    manage: all
  superadmin:
    manage: all
  admin:
    manage: all
  accountant:
    manage: all
  compliance:
    manage: all
  manager:
    manage: all
  support:
    manage: all
  technical:
    manage: all
  broker:
    manage: all
  trader:
    manage: all
  maker:
    manage: all
