connect:
  host: <%= ENV.fetch('RABBITMQ_HOST', 'localhost') %>
  port: <%= ENV.fetch('RABBITMQ_PORT', '5672') %>
  username: <%= ENV.fetch('RABBITMQ_USER', 'guest') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD', 'guest') %>

exchange:
  trade:
    name: peatio.trade
    type: headers
  notification:
    name: peatio.notification
    type: direct
  orderbook:
    name: peatio.orderbook
    type: fanout

queue:
  matching:
    name: peatio.matching
    durable: true
  slave_book:
    name: peatio.orderbook.slave
    durable: true
  new_trade:
    name: peatio.trade.new
    durable: true
  order_processor:
    name: peatio.order.processor
    durable: true
  market_ticker:
    name: peatio.trade.market_ticker
  pusher_market:
    name: peatio.pusher.market
  pusher_member:
    name: peatio.pusher.member
  withdraw_coin:
    name: peatio.withdraw.coin
  deposit_coin:
    name: peatio.deposit.coin
  deposit_coin_address:
    name: peatio.deposit.coin.address
    durable: true

binding:
  matching:
    queue: matching
    clean_start: true
  slave_book:
    queue: slave_book
    exchange: orderbook
  trade_executor:
    queue: new_trade
  order_processor:
    queue: order_processor
  market_ticker:
    queue: market_ticker
    exchange: trade
  pusher_market:
    queue: pusher_market
    exchange: trade
  pusher_member:
    queue: pusher_member
  withdraw_coin:
    queue: withdraw_coin
  deposit_coin:
    queue: deposit_coin
  deposit_coin_address:
    queue: deposit_coin_address

channel:
  trade_executor:
    prefetch: 5
  order_processor:
    prefetch: 5
