default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 8).to_i * ENV.fetch("WEB_CONCURRENCY", 1).to_i %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DATABASE_PORT', 3306) %>
  username: <%= ENV.fetch('DATABASE_USER', 'root') %>
  password: <%= ENV['DATABASE_PASS'] %>

development:
  <<: *default
  database: peatio_development

test:
  <<: *default
  database: peatio_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV.fetch('DATABASE_NAME', 'peatio_production') %>
