- id: 200
  key: satoshi
  currency: btc
  sort_order: 2
  min_confirm: 1
  max_confirm: 6
- id: 300
  key: protoshare
  currency: pts
  sort_order: 9
  min_confirm: 1
  max_confirm: 6
- id: 400
  key: bank
  currency: cny
  sort_order: 1
  bank_accounts:
    -
      bank: 招商银行
      branch: 北京双榆树支行
      holder: 邱亮
      account: 6214 8501 0176 3297
- id: 500
  key: dogecoin
  currency: doge
  sort_order: 10
  min_confirm: 1
  max_confirm: 6
- id: 600
  key: bitsharesx
  currency: btsx
  sort_order: 3
  min_confirm: 10
  max_confirm: 51
- id: 700
  key: keyid
  currency: dns
  sort_order: 4
  min_confirm: 10
  max_confirm: 51
