# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  # This secret key is used for verifying digital signatures of cookies.
  #
  # You can generate one by running:
  #
  #   bundle exec rake secret
  #
  # Development and test environments already include sample secret keys.
  secret_key_base: ~

development:
  <<: *defaults
  secret_key_base: ec7ffa7f1e53b586f2ad072518776a153b14f40ea77e5aa17b9b3ab5145ac29f018c2da13c626102b2d7c749b60f8fc81798579a7e820b96821d431b5fc144c3

test:
  <<: *defaults
  secret_key_base: 2c3cdc3e0bc14d5260250570be0961de2f974c4f3e15b6004734d9e587ce9f47da248f20dc1707a5bb555d879a5494641f4b1a01ca6066df2b783943914ebcd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
