- id: 200
  key: satoshi
  currency: btc
  fixed: 4
  fee: 0.0001
  sort_order: 2
- id: 300
  key: protoshare
  currency: pts
  fixed: 4
  fee: 0.0001
  sort_order: 4
- id: 400
  key: bank
  currency: cny
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0
  proportion: true
  sort_order: 1
- id: 500
  key: dogecoin
  currency: doge
  fixed: 0
  fee: 1
  sort_order: 5
- id: 600
  key: bitsharesx
  currency: btsx
  fixed: 5
  fee: 0.1
  sort_order: 3
- id: 700
  key: keyid
  currency: dns
  fixed: 5
  fee: 0.1
  sort_order: 4
